name: Java Quarkus CI/CD with Maven

on:
  push:
    branches: [ master, develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: list Directories
      run: ls -lha

    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
      
    - name: Show Maven Version
      run: mvn --version
      
    - name: Show Java Version
      run: java --version
      
    - name: Show Git Version
      run: git --version
      
    - name: Build Clean Maven Install
      run: mvn clean install -DskipTests=true
      
    - name: Build Clean Maven Verify
      run: mvn clean verify -DskipTests=true
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Image   
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: .
        push: true
        tags: devmenorzera/ms-quarkus-banking-client:latest
          
    - name: Finish Workflow
      run: echo Finished Workflow
