name: Java Quarkus CICD with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
      
    - name: Show Maven Version
      run: mvn -version
      
    - name: Show Java Version
      run: java -version  
      
    - name: Show Git Version
      run: git --version
      
    - name: Build Clean Maven Install
      run: mvn clean install -DskipTests=true
      
    - name: Build Clean Maven Verify
      run: mvn clean verify -DskipTests=true
    
    - name: Build Docker
      run: docker build -t nginx:latest
      
    - name: Run Docker
      run: docker run --name=nginx -d -p 80:80 nginx:latest

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
